batchling create\
 --id together\
 --model "deepseek-ai/DeepSeek-V3"\
 --name "testing DeepSeek-V3"\
 --description "experiment testing DeepSeek-V3"\
 --raw-file-path tests/test_data/raw_file_countries.jsonl\
 --placeholders-path tests/test_data/placeholders_capitals.jsonl\
 --processed-file-path input_capitals_together.jsonl\
 --provider together\
 --endpoint /v1/chat/completions\
 --results-file-path output/result_capitals_together.jsonl
