batchling create\
 --id openai\
 --model "gpt-4o"\
 --name "exp name"\
 --description "exp description"\
 --raw-file-path tests/test_data/template_messages_countries.jsonl\
 --placeholders-path tests/test_data/placeholders_capitals.jsonl\
 --processed-file-path input_capitals_oai.jsonl\
 --provider openai\
 --endpoint /v1/chat/completions\
 --results-file-path output/result_capitals_openai.jsonl
