batchling create\
 --id groq\
 --model "llama-3.1-8b-instant"\
 --name "testing llama-3.1-8b-instant"\
 --description "experiment testing llama-3.1-8b-instant"\
 --template-messages-path tests/test_data/template_messages_countries.jsonl\
 --placeholders-path tests/test_data/placeholders_capitals.jsonl\
 --input-file-path input_capitals_groq.jsonl\
 --provider groq\
 --endpoint /v1/chat/completions\
 --output-file-path output/result_capitals_groq.jsonl
