batchling create\
 --id anthropic\
 --model "claude-3-haiku-20240307"\
 --name "experiment haiku"\
 --description "experiment testing claude-3-haiku-20240307"\
 --template-messages-path tests/test_data/template_messages_countries.jsonl\
 --placeholders-path tests/test_data/placeholders_capitals.jsonl\
 --input-file-path input_capitals_anthropic.jsonl\
 --provider anthropic\
 --endpoint /v1/chat/completions\
 --output-file-path output/result_capitals_anthropic.jsonl\
 --max-tokens-per-request 100
