batchling create\
 --id mistral\
 --model "mistral-small-latest"\
 --name "testing mistral-small-latest"\
 --description "experiment testing mistral-small-latest"\
 --raw-file-path tests/test_data/template_messages_countries.jsonl\
 --placeholders-path tests/test_data/placeholders_capitals.jsonl\
 --processed-file-path input_capitals_mistral.jsonl\
 --provider mistral\
 --endpoint /v1/chat/completions\
 --results-file-path output/result_capitals_mistral.jsonl
